### ISSUE TITLE
Convert to SE facing installer rather than source installer

### ISSUE THREAD

**Issue by earcuri** [PaloAltoNetworks/pan-tort#1]
The newer versions of tort are built to use docker containers and load the source from the container.  By changing this repository to use only the docker compose and containers, this alleviates the SEs from having to actually build and run the source and the containers will run all of the time.  This is especially beneficial in the LIaB setup.  
The source itself will move to the pan-tort-source repository.

**Comment by punisherVX** [comment]
This is fixed in 2e5ae64 and latest release at this time.
